name: cg-idps
channels:
  - conda-forge
  - defaults
dependencies:
  - jinja2
  - matplotlib
  - mdtraj
  - notebook
  - numpy
  - openpyxl
  - pandas
  - python=3.8
  - scikit-learn
  - scipy
  - xlrd
