name: cg-idps
channels:
  - conda-forge
  - defaults
dependencies:
  - jinja2
  - matplotlib
  - mdtraj
  - notebook
  - numpy
  - openpyxl
  - pandas
  - python=3.8
  - scikit-learn
  - scipy
  - xlrd
  - hoomd
  - pip
  - pip:
    - biopython
    - cython
    - mdanalysis==1.0
    - ray==1.0
    - PeptideBuilder
    - DEERPREdict
